// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/juego.proto

package juego

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MovimientoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JugadorId     string                 `protobuf:"bytes,1,opt,name=jugador_id,json=jugadorId,proto3" json:"jugador_id,omitempty"`
	Direccion     string                 `protobuf:"bytes,2,opt,name=direccion,proto3" json:"direccion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovimientoRequest) Reset() {
	*x = MovimientoRequest{}
	mi := &file_proto_juego_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovimientoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovimientoRequest) ProtoMessage() {}

func (x *MovimientoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juego_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovimientoRequest.ProtoReflect.Descriptor instead.
func (*MovimientoRequest) Descriptor() ([]byte, []int) {
	return file_proto_juego_proto_rawDescGZIP(), []int{0}
}

func (x *MovimientoRequest) GetJugadorId() string {
	if x != nil {
		return x.JugadorId
	}
	return ""
}

func (x *MovimientoRequest) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

type MovimientoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resultado     string                 `protobuf:"bytes,1,opt,name=resultado,proto3" json:"resultado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovimientoResponse) Reset() {
	*x = MovimientoResponse{}
	mi := &file_proto_juego_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovimientoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovimientoResponse) ProtoMessage() {}

func (x *MovimientoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juego_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovimientoResponse.ProtoReflect.Descriptor instead.
func (*MovimientoResponse) Descriptor() ([]byte, []int) {
	return file_proto_juego_proto_rawDescGZIP(), []int{1}
}

func (x *MovimientoResponse) GetResultado() string {
	if x != nil {
		return x.Resultado
	}
	return ""
}

var File_proto_juego_proto protoreflect.FileDescriptor

const file_proto_juego_proto_rawDesc = "" +
	"\n" +
	"\x11proto/juego.proto\x12\x05juego\"P\n" +
	"\x11MovimientoRequest\x12\x1d\n" +
	"\n" +
	"jugador_id\x18\x01 \x01(\tR\tjugadorId\x12\x1c\n" +
	"\tdireccion\x18\x02 \x01(\tR\tdireccion\"2\n" +
	"\x12MovimientoResponse\x12\x1c\n" +
	"\tresultado\x18\x01 \x01(\tR\tresultado2S\n" +
	"\fJuegoService\x12C\n" +
	"\fMoverJugador\x12\x18.juego.MovimientoRequest\x1a\x19.juego.MovimientoResponseB\x16Z\x14mi-juego/proto;juegob\x06proto3"

var (
	file_proto_juego_proto_rawDescOnce sync.Once
	file_proto_juego_proto_rawDescData []byte
)

func file_proto_juego_proto_rawDescGZIP() []byte {
	file_proto_juego_proto_rawDescOnce.Do(func() {
		file_proto_juego_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_juego_proto_rawDesc), len(file_proto_juego_proto_rawDesc)))
	})
	return file_proto_juego_proto_rawDescData
}

var file_proto_juego_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_juego_proto_goTypes = []any{
	(*MovimientoRequest)(nil),  // 0: juego.MovimientoRequest
	(*MovimientoResponse)(nil), // 1: juego.MovimientoResponse
}
var file_proto_juego_proto_depIdxs = []int32{
	0, // 0: juego.JuegoService.MoverJugador:input_type -> juego.MovimientoRequest
	1, // 1: juego.JuegoService.MoverJugador:output_type -> juego.MovimientoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_juego_proto_init() }
func file_proto_juego_proto_init() {
	if File_proto_juego_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_juego_proto_rawDesc), len(file_proto_juego_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_juego_proto_goTypes,
		DependencyIndexes: file_proto_juego_proto_depIdxs,
		MessageInfos:      file_proto_juego_proto_msgTypes,
	}.Build()
	File_proto_juego_proto = out.File
	file_proto_juego_proto_goTypes = nil
	file_proto_juego_proto_depIdxs = nil
}
